### PR TITLE
ecp5ddrphy: Reliability improvements

### PR DESCRIPTION
**Pull request by daveshah1**
- Add DDRDEL & DELAYF
 - Dynamic READCLKSEL adjustment
 - Enable differential termination on DQS according to Lattice provided LPF

Not sure how correct all of this is, but I now seem to see the training pattern on some of the DQs (but for some reason not all) consistently

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks! Do you also changes in the returned data when changing the delay?
(i'm not able to test now, but will do very soon, tomorrow morning in the worst case)

**Comment by daveshah1** [comment]
Strangely, sometimes, not always. I modified the script to run 10 times at each delay, in order to distinguish random variation from genuine changes. I'm still not sure if READCLKSEL is the only thing that we need to adjust, but Lattice's TN1265 says
> Once READ1/0 positions the READ pulse, READCLKSEL2/1/0 can be used to shift the READ pulse by 1/4T per step. With the total eight possible combinations from “000” to “111”, READCLKSEL2/1/0 covers the READ pulse shift up to a whole 2T timing window. If BURSTDET is asserted with a certain READCLKSEL2/1/0 value, it indicates that the READ pulse has been located to the optimal position. If no BURSTDET is asserted during this step, the READ pulse needs to be moved to the next timing window.

**Comment by daveshah1** [comment]
Changing to adjusting the DELAYF seems to make more of a useful difference. Interestingly, I've noticed this sort of pattern a bit

```
delay: 41 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 41 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 41 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 42 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 42 |dq0: 0b00001010, dq1: 0b00000000, dq2: 0b00000000, dq3: 0b00000000, dq4: 0b00001010, dq5: 0b00000000, dq6: 0b00000000, dq7: 0b00000000, 
delay: 42 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 42 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 42 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 43 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 43 |dq0: 0b00001010, dq1: 0b00000000, dq2: 0b00000000, dq3: 0b00000000, dq4: 0b00000000, dq5: 0b00000000, dq6: 0b00000000, dq7: 0b00000000, 
delay: 43 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 43 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 43 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 44 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 44 |dq0: 0b00001010, dq1: 0b00000000, dq2: 0b00000000, dq3: 0b00000000, dq4: 0b00000000, dq5: 0b00000000, dq6: 0b00000000, dq7: 0b00000000, 
delay: 44 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 44 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 44 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 45 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 45 |dq0: 0b00001010, dq1: 0b00000000, dq2: 0b00000000, dq3: 0b00000000, dq4: 0b00000000, dq5: 0b00000000, dq6: 0b00000000, dq7: 0b00000000, 
delay: 45 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
delay: 45 |dq0: 0b00001010, dq1: 0b00001010, dq2: 0b00001010, dq3: 0b00001010, dq4: 0b00001010, dq5: 0b00001010, dq6: 0b00001010, dq7: 0b00001010, 
```

where some bits are consistently giving 0000 instead of 1010 every 1 out of 5 reads. Almost seems like a bitslip type issue

**Comment by enjoy-digital** [comment]
Sorry, haven't tested yet, do you see an improvement with the latest commit?

**Comment by daveshah1** [comment]
Marginally, but it still doesn't seem perfect. I'm continuing to investigate

**Comment by enjoy-digital** [comment]
I don't know if you are aware, but you can run `test_analyzer.py` while running `test_sdram.py` to see what happen in the fabric while doing the read.

**Comment by daveshah1** [comment]
Playing with that now, and seeing some odd behaviour.

Right now, the reliability issue seems to be that sometimes after loading the bitstream it works well - seeing the expected pattern pretty stably, other times it almost always reads all zeroes. Soft resets won't change this "mode", only reloading the FPGA.

What is strange is that in the former, working, case the analyser gets stuck on "[uploading]... |>             0%" whereas in the failing, "almost-all-zero" case the analyser downloads fine. Is there perhaps some compression that would mean the zeros result in different analyser behaviour?

**Comment by daveshah1** [comment]
This is very strange indeed. I have removed all analyser inputs except one "datavalid" signal from DQSBUFM and I am still seeing that the analyser consistently for runs when the read pattern returns all 0s; and the analyser consistently crashes during upload when the read pattern is correct.

**Comment by enjoy-digital** [comment]
The behaviour you saw was cause by a glitch on the uart during bistream loading and seems to be fixed with  https://github.com/enjoy-digital/litex/commit/ff155a474d12b62fb84db0ca07d2577687c5c141. Printing p0/p1 in the read leveling loop could also help debug. The first thing we want to see is if we are able to modified the returned value by incrementing the delays.

**Comment by daveshah1** [comment]
Thanks! After also fixing the width (should be 16 not 8) in the test script, everything is behaving much better now.

**Comment by enjoy-digital** [comment]
Doing some tests with https://github.com/enjoy-digital/versa_ecp5_dram/pull/2/commits/9e2b8b77aff70a605fa636cd12b2668bf8f3031a, we see that we are able to write/read some data to the DDR3. (everything is not there and not at the right place, but that's still a good point).

Looking at another halfrate phy: https://github.com/enjoy-digital/litedram/blob/write_latency/litedram/phy/s7ddrphy_halfrate_bl8.py, i think the read part should probably be something like this:
````
                dq_bitslip = BitSlip(4)
                self.comb += dq_bitslip.i.eq(dq_i_data)
                self.sync += \
                    If(self._dly_sel.storage[i],
                        If(self._rdly_dq_bitslip_rst.re,
                            dq_bitslip.value.eq(0)
                        ).Elif(self._rdly_dq_bitslip.re,
                            dq_bitslip.value.eq(dq_bitslip.value + 1)
                        )
                    )
                self.submodules += dq_bitslip
                dq_bitslip_o_d = Signal(4)
                self.sync += dq_bitslip_o_d.eq(dq_bitslip.o)
                self.comb += [
                    self.dfi.phases[0].rddata[0*databits+j].eq(dq_bitslip_o_d[3]), self.dfi.phases[0].rddata[1*databits+j].eq(dq_bitslip_o_d[2]),
                    self.dfi.phases[0].rddata[2*databits+j].eq(dq_bitslip_o_d[1]), self.dfi.phases[0].rddata[3*databits+j].eq(dq_bitslip_o_d[0]),
                    self.dfi.phases[1].rddata[0*databits+j].eq(dq_bitslip.o[3]), self.dfi.phases[1].rddata[1*databits+j].eq(dq_bitslip.o[2]),
                    self.dfi.phases[1].rddata[2*databits+j].eq(dq_bitslip.o[1]), self.dfi.phases[1].rddata[3*databits+j].eq(dq_bitslip.o[0]),
                ]
````

**Comment by daveshah1** [comment]
I will have a look at that code sample next.

The idea of 9e2b8b7 was to replicate the "coarse" read pulse positioning algorithm described on TN1265 page 30 moving the READ pulse position and then adjusting `READCLKSEL`. For one of the many working values 0x1A (READ pulse delayed by 3 clocks, `READCLKSEL`=3'b010), the resulting waveform seems to match that described in TN1265 with `BURST_DET` being de-asserted then asserted; suggesting that the DQSBUF side of things is up and running.

screenshot from 2019-02-16 16-24-32

It is possible that the latency through the DQSBUF & input "FIFO" is not constant, and that we should be looking at the DATAVALID signal to determine when to sample the input data.

**Comment by daveshah1** [comment]
With that change applied, running the test I now see:

```
0: 0x00000001, 0x00000000 KO
1: 0x00000001, 0x00000001 OK
2: 0x00000039, 0x00000002 KO
3: 0x00000001, 0x00000003 KO
4: 0x00000005, 0x00000004 KO
5: 0x00000005, 0x00000005 OK
6: 0x0000003d, 0x00000006 KO
7: 0x00000005, 0x00000007 KO
8: 0x00000009, 0x00000008 KO
9: 0x00000009, 0x00000009 OK
10: 0x00000001, 0x0000000a KO
11: 0x00000009, 0x0000000b KO
12: 0x0000000d, 0x0000000c KO
13: 0x0000000d, 0x0000000d OK
14: 0x00000005, 0x0000000e KO
15: 0x0000000d, 0x0000000f KO
16: 0x00000011, 0x00000010 KO
17: 0x00000011, 0x00000011 OK
18: 0x00000009, 0x00000012 KO
19: 0x00000011, 0x00000013 KO
20: 0x00000015, 0x00000014 KO
21: 0x00000015, 0x00000015 OK
22: 0x0000000d, 0x00000016 KO
23: 0x00000015, 0x00000017 KO
24: 0x00000019, 0x00000018 KO
25: 0x00000019, 0x00000019 OK
26: 0x00000011, 0x0000001a KO
27: 0x00000019, 0x0000001b KO
28: 0x0000001d, 0x0000001c KO
29: 0x0000001d, 0x0000001d OK
30: 0x00000015, 0x0000001e KO
31: 0x0000001d, 0x0000001f KO
32: 0x00000021, 0x00000020 KO
33: 0x00000021, 0x00000021 OK
34: 0x00000019, 0x00000022 KO
35: 0x00000021, 0x00000023 KO
36: 0x00000025, 0x00000024 KO
37: 0x00000025, 0x00000025 OK
38: 0x0000001d, 0x00000026 KO
39: 0x00000025, 0x00000027 KO
40: 0x00000029, 0x00000028 KO
41: 0x00000029, 0x00000029 OK
42: 0x00000021, 0x0000002a KO
43: 0x00000029, 0x0000002b KO
44: 0x0000002d, 0x0000002c KO
45: 0x0000002d, 0x0000002d OK
46: 0x00000025, 0x0000002e KO
47: 0x0000002d, 0x0000002f KO
48: 0x00000031, 0x00000030 KO
49: 0x00000031, 0x00000031 OK
50: 0x00000029, 0x00000032 KO
51: 0x00000031, 0x00000033 KO
52: 0x00000035, 0x00000034 KO
53: 0x00000035, 0x00000035 OK
54: 0x0000002d, 0x00000036 KO
55: 0x00000035, 0x00000037 KO
56: 0x00000039, 0x00000038 KO
57: 0x00000039, 0x00000039 OK
58: 0x00000031, 0x0000003a KO
59: 0x00000039, 0x0000003b KO
60: 0x0000003d, 0x0000003c KO
61: 0x0000003d, 0x0000003d OK
62: 0x00000035, 0x0000003e KO
63: 0x0000003d, 0x0000003f KO
```

**Comment by enjoy-digital** [comment]
Thanks. The core will expect a constant latency from the phy, but we could add a small fifo with writes done on
DATAVALID and reads done by the flow control logic.

**Comment by enjoy-digital** [comment]
I did some test and some experiment yesterday based on your last commit:

When looking with the analyzer and enabling random data and triggering on the first access, i'm able to see the correct 64-bit value on dfi_p0_rddata when playing with bitslip but the latency is higher that what is expected by the core and then returned wishbone data is not correct. When changing the latency in the phy, i'm no longer able to see the valid data on dfi_p0_rddata and don't explain it since it should not have this behaviour but only shift the rddata_valid.

i also added some CSR to monitor the burstdet and ease this calibration. I'm also not sure the DELAYF in the dq input is needed.

The work is here: https://github.com/enjoy-digital/versa_ecp5_dram/commit/a752deea627435fc79abbaf777b6bcb095b88e5f

**Comment by daveshah1** [comment]
Delaying write data & mask by one cycle to match DQS seems to have improved things, it seems like almost all the right data is now there but just in the wrong order. 

```
0: 0x3c88f35f, 0x3c6ef35f KO
1: 0x00000000, 0x3c88596c KO
2: 0x3cbbbf79, 0x3ca1bf79 KO
3: 0x3ca1596c, 0x3cbb2586 KO
4: 0x3ced8b93, 0x3cd48b93 KO
5: 0x00000000, 0x3cedf1a0 KO
6: 0x3d2057ad, 0x3d0757ad KO
7: 0x3d07f1a0, 0x3d20bdba KO
8: 0x3d5323c7, 0x3d3a23c7 KO
```

**Comment by daveshah1** [comment]
As of 007424c, I am now received 7/8 halfwords (the upper 16 bits of word 0 are always wrong, but consistently read the same wrong value across multiple runs) correctly, which seems promising

```
0: 0x057af35f, 0x3c6ef35f KO
1: 0x3c88596c, 0x3c88596c OK
2: 0x3ca1bf79, 0x3ca1bf79 OK
3: 0x3cbb2586, 0x3cbb2586 OK
4: 0xd7a38b93, 0x3cd48b93 KO
5: 0x3cedf1a0, 0x3cedf1a0 OK
6: 0x3d0757ad, 0x3d0757ad OK
7: 0x3d20bdba, 0x3d20bdba OK
8: 0xb08123c7, 0x3d3a23c7 KO
9: 0x3d5389d4, 0x3d5389d4 OK
10: 0x3d6cefe1, 0x3d6cefe1 OK
11: 0x3d8655ee, 0x3d8655ee OK
12: 0xe307bbfb, 0x3d9fbbfb KO
13: 0x3db92208, 0x3db92208 OK
14: 0x3dd28815, 0x3dd28815 OK
15: 0x3debee22, 0x3debee22 OK
```

**Comment by enjoy-digital** [comment]
Good! When i was doing tests yesterday, i was able to see all the datas of a 64-bit word with the analyzer. So i'm wondering if the corrupted data could be related to the change you did on the write side.

**Comment by enjoy-digital** [comment]
When you trigger the analyzer on a read with `test_analyzer.py,` run the `test_sdram.py` are you able to see the 0x3c6e somewhere on dfi_p0_rddata? If not, then the issue is probably on the writes. On test you can also do to confirm that: do a power off/power on, load the fpga, run comment the data write in`test_sdram.py` and run it. Then un-comment the write and compare the two results. If the first word is the same then the issue is probably on the writes.

**Comment by daveshah1** [comment]
I don't see 0x3c6e anywhere looking at the read data in the analyser. Running with writes commented-out after a period of power off gives the bad halfword as 0x0000 (with other halfwords being random data). I also notice that this changes with repeated runs with writes commented out. The suspicious 0x0000 points to an issue on the read side.

Reverting the change I made to writes makes things significantly worse again:

```
0: 0x077afbfc, 0x3c6ef35f KO
1: 0xbeeb7fee, 0x3c88596c KO
2: 0x3c6ef35f, 0x3ca1bf79 KO
3: 0x3c88596c, 0x3cbb2586 KO
4: 0x00006b33, 0x3cd48b93 KO
5: 0xaeffebe7, 0x3cedf1a0 KO
6: 0x3cd48b93, 0x3d0757ad KO
7: 0x3cedf1a0, 0x3d20bdba KO
8: 0x0000fff7, 0x3d3a23c7 KO
9: 0xfc84cdbc, 0x3d5389d4 KO
10: 0x3d3a23c7, 0x3d6cefe1 KO
11: 0x3d5389d4, 0x3d8655ee KO
12: 0x000067ff, 0x3d9fbbfb KO
13: 0xfe7baae7, 0x3db92208 KO
14: 0x3d9fbbfb, 0x3dd28815 KO
15: 0x3db92208, 0x3debee22 KO
```

**Comment by daveshah1** [comment]
Moving forward... Adding the DQS pre-/post-amble during writes now means that the test is 100% passing, but only every other time you run it. The remaining problem is now solely on the read side (tested by commenting out writes, and the "every other run" behaviour still holds). The failing runs produce output like:
```
0: 0x41fd4637, 0x3c6ef35f KO
1: 0x3c6ef35f, 0x3c88596c KO
2: 0x3c88596c, 0x3ca1bf79 KO
3: 0x3ca1bf79, 0x3cbb2586 KO
4: 0x4262de6b, 0x3cd48b93 KO
5: 0x3cd48b93, 0x3cedf1a0 KO
6: 0x3cedf1a0, 0x3d0757ad KO
7: 0x3d0757ad, 0x3d20bdba KO
8: 0x00010000, 0x3d3a23c7 KO
9: 0x3d3a23c7, 0x3d5389d4 KO
10: 0x3d5389d4, 0x3d6cefe1 KO
11: 0x3d6cefe1, 0x3d8655ee KO
12: 0x00110000, 0x3d9fbbfb KO
13: 0x3d9fbbfb, 0x3db92208 KO
14: 0x3db92208, 0x3dd28815 KO
15: 0x3dd28815, 0x3debee22 KO
```

I suspect this might be related to the DQSBUF READ control.

**Comment by enjoy-digital** [comment]
Thanks, i'll probably do some tests this evening.

**Comment by daveshah1** [comment]
Obeying the requirement to assert PAUSE while changing READCLKSEL seems to have fixed the "only working every other run" issue. It would be great to see if you can reproduce this working now!

**Comment by enjoy-digital** [comment]
With https://github.com/enjoy-digital/versa_ecp5_dram/tree/improve2:
````
>python3 test_sdram.py 
Release reset
Bring CKE high
Load Mode Register 2, CWL=5
Load Mode Register 3
Load Mode Register 1
Load Mode Register 0, CL=6, BL=8
ZQ Calibration
DQS taps: 0
Read leveling...
delay: 0 | burst_det : 1
delay: 1 | burst_det : 0
delay: 2 | burst_det : 0
delay: 3 | burst_det : 0
delay: 4 | burst_det : 0
delay: 5 | burst_det : 0
delay: 6 | burst_det : 0
delay: 7 | burst_det : 0
delay: 8 | burst_det : 0
delay: 9 | burst_det : 0
delay: 10 | burst_det : 0
delay: 11 | burst_det : 0
delay: 12 | burst_det : 0
delay: 13 | burst_det : 0
delay: 14 | burst_det : 0
delay: 15 | burst_det : 0
delay: 16 | burst_det : 0
delay: 17 | burst_det : 0
delay: 18 | burst_det : 0
delay: 19 | burst_det : 0
delay: 20 | burst_det : 0
delay: 21 | burst_det : 0
delay: 22 | burst_det : 0
delay: 23 | burst_det : 0
delay: 24 | burst_det : 2
0: 0x3c6ef35f, 0x3c6ef35f OK
1: 0x3c88596c, 0x3c88596c OK
2: 0x3ca1bf79, 0x3ca1bf79 OK
3: 0x3cbb2586, 0x3cbb2586 OK
4: 0x3cd48b93, 0x3cd48b93 OK
5: 0x3cedf1a0, 0x3cedf1a0 OK
6: 0x3d0757ad, 0x3d0757ad OK
7: 0x3d20bdba, 0x3d20bdba OK
8: 0x3d3a23c7, 0x3d3a23c7 OK
9: 0x3d5389d4, 0x3d5389d4 OK
10: 0x3d6cefe1, 0x3d6cefe1 OK
11: 0x3d8655ee, 0x3d8655ee OK
12: 0x3d9fbbfb, 0x3d9fbbfb OK
13: 0x3db92208, 0x3db92208 OK
14: 0x3dd28815, 0x3dd28815 OK
15: 0x3debee22, 0x3debee22 OK
16: 0x3e05542f, 0x3e05542f OK
17: 0x3e1eba3c, 0x3e1eba3c OK
18: 0x3e382049, 0x3e382049 OK
19: 0x3e518656, 0x3e518656 OK
20: 0x3e6aec63, 0x3e6aec63 OK
21: 0x3e845270, 0x3e845270 OK
22: 0x3e9db87d, 0x3e9db87d OK
23: 0x3eb71e8a, 0x3eb71e8a OK
24: 0x3ed08497, 0x3ed08497 OK
25: 0x3ee9eaa4, 0x3ee9eaa4 OK
26: 0x3f0350b1, 0x3f0350b1 OK
27: 0x3f1cb6be, 0x3f1cb6be OK
28: 0x3f361ccb, 0x3f361ccb OK
29: 0x3f4f82d8, 0x3f4f82d8 OK
30: 0x3f68e8e5, 0x3f68e8e5 OK
31: 0x3f824ef2, 0x3f824ef2 OK
32: 0x3f9bb4ff, 0x3f9bb4ff OK
33: 0x3fb51b0c, 0x3fb51b0c OK
34: 0x3fce8119, 0x3fce8119 OK
35: 0x3fe7e726, 0x3fe7e726 OK
36: 0x40014d33, 0x40014d33 OK
37: 0x401ab340, 0x401ab340 OK
38: 0x4034194d, 0x4034194d OK
39: 0x404d7f5a, 0x404d7f5a OK
40: 0x4066e567, 0x4066e567 OK
41: 0x40804b74, 0x40804b74 OK
42: 0x4099b181, 0x4099b181 OK
43: 0x40b3178e, 0x40b3178e OK
44: 0x40cc7d9b, 0x40cc7d9b OK
45: 0x40e5e3a8, 0x40e5e3a8 OK
46: 0x40ff49b5, 0x40ff49b5 OK
47: 0x4118afc2, 0x4118afc2 OK
48: 0x413215cf, 0x413215cf OK
49: 0x414b7bdc, 0x414b7bdc OK
50: 0x4164e1e9, 0x4164e1e9 OK
51: 0x417e47f6, 0x417e47f6 OK
52: 0x4197ae03, 0x4197ae03 OK
53: 0x41b11410, 0x41b11410 OK
54: 0x41ca7a1d, 0x41ca7a1d OK
55: 0x41e3e02a, 0x41e3e02a OK
56: 0x41fd4637, 0x41fd4637 OK
57: 0x4216ac44, 0x4216ac44 OK
58: 0x42301251, 0x42301251 OK
59: 0x4249785e, 0x4249785e OK
60: 0x4262de6b, 0x4262de6b OK
61: 0x427c4478, 0x427c4478 OK
62: 0x4295aa85, 0x4295aa85 OK
63: 0x42af1092, 0x42af1092 OK
0 errors
````
:)

**Comment by daveshah1** [comment]
Playing around I notice that bitslip is sometimes 0 and sometimes 2, this seems to change when loading the bitstream but then seems stable once it's running.

If you use the 'ddr_mem' interface wizard in Diamond (inside Clarity Designer), then I notice that it generates some soft logic, a small FSM to handle control of reset, the ECLKSYNC and the DDRDLL. I wonder if the absence of that is leading to unpredictable startup behaviour (some comments in TN1265 suggest it is needed for this reason).

**Comment by enjoy-digital** [comment]
I have the exact same behaviour. Your explanation make sense, we should try to implement the same startup logic than with `ddr_mem` wizard.

**Comment by daveshah1** [comment]
Added the proper startup FSM and it seems rock solid now.

**Comment by enjoy-digital** [comment]
Great, thanks! Do you want to merge the pull request in master?

**Comment by daveshah1** [comment]
Sure, go ahead!

**Comment by enjoy-digital** [comment]
OK doing that now. I'll then test with a CPU, maybe do some refactoring and once rock solid with a CPU, we could integrate the phy in LiteDRAM and the target in LiteX.

**Pull request merged**
